---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: debian-9
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[mailhog::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
